data class PS(val y: Int, val x: Int)

fun main() {
    val input2 = """.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............""".split("\n").map { it.toCharArray() }

    val input = readInput("day07").map { it.toCharArray() }

    var dp = Array(input.size) { Array(input[0].size) { 0L } }
    dp[0][input[0].indexOf('S')] = 1
    for (y in 1 until input.size) {
        for (x in 0 until input[0].size) {
            if (input[y][x] == '.') {
                dp[y][x] += dp[y - 1][x]
            } else {
                dp.getOrNull(y)?.getOrNull(x + 1)?.let { dp[y][x + 1] += dp[y - 1][x] }
                dp.getOrNull(y)?.getOrNull(x - 1)?.let { dp[y][x - 1] += dp[y - 1][x] }
            }
        }

    }

    println(dp.last().sum())
}
